[tool.poetry]
name = "news"
version = "0.1.0"
description = ""
authors = ["pnoryk <pnoryk@wiseweb.by>"]

[tool.poetry.dependencies]
python = "^3.9.0"
Django = "^3.1.5"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
